### ISSUE TITLE
FakerLibrary cannot be initialized with multiple locales

### ISSUE THREAD

**Issue by jrfigura** [guykisel/robotframework-faker#42]
Faker Library supports initialization with multiple locales:
from faker import Faker
fake = Faker(['it_IT', 'en_US', 'ja_JP'])
for _ in range(10):
    print(fake.name())

Whenever I try to initialize library with multiple locales it fails with error:
Error in file '/app/robot/keywords/InventoryImportKeywords.robot': Initializing test library 'FakerLibrary' with arguments [ locale=['ja_JP', 'de_DE', 'en_US'] ] failed: AttributeError: 'list' object has no attribute 'replace'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/FakerLibrary/keywords.py", line 42, in __init__
    self._fake = faker.factory.Factory.create(locale, providers)
  File "/usr/local/lib/python3.8/site-packages/faker/factory.py", line 35, in create
    locale = locale.replace('-', '_') if locale else DEFAULT_LOCALE

In factory.py file we always treat locale variable as a string with single argument and line:
locale = locale.replace('-', '_') if locale else DEFAULT_LOCALE
causes this issue

Would be super nice to have initialization with multiple locales implemented

**Comment by damies13** [comment]
FYI - I believe this is possible, just not well documented, i found this example in another issue and have tried it, it seems to work for me:
https://github.com/MarketSquare/robotframework-faker/issues/86#issuecomment-2028492306
